global:
  resolve_timeout: 5m

route:
  receiver: 'discord-webhook'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'discord-webhook'
    webhook_configs:
      - url: 'http://discord_bridge:8080/alert'
        send_resolved: true
