global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'cockpit'
    metrics_path: '/api/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['host.docker.internal:3000']
